angular.module('myApp', []).controller('clientsCtrl', function($scope) {
    $scope.clients = [{
            location: 'Raymonds, Civil Lines, Allahabad',
            title: 'Raymond',
            img: 'raymond',
            key1: 'Duplex : ',
            key2: 'Cartons : ',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '41.96 kg',
            value2: '172.085 kg',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        }, {
            location: 'Killer, Civil Lines, Allahabad',
            title: 'Killer',
            img: 'killer',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: 'Mix : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '12.760 kg',
            value2: '1.720 kg',
            value3: '8.165 kg',
            value4: '',
            value5: '',
            value6: ''
        },  {
            location: 'Arrow, Civil Lines, Allahabad',
            title: 'Arrow',
            img: 'arrow',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: 'Duplex : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '22.515 kg',
            value2: '1 kg',
            value3: '1.150 kg',
            value4: '',
            value5: '',
            value6: ''
        }, {
            location: 'Linerty, Civil Lines, Allahabad',
            title: 'Liberty',
            img: 'liberty',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '30 kg',
            value2: '1.550 kg',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        }, {
            location: 'Maharaja Footwear KP Kakkar Road,South Malaka ,Allahabad',
            title: 'Maharaja Footwear',
            img: 'maharaja',
            key1: 'Recyclable Material : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '150 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        }, {
            location: 'Patanjali,Naini ,Allahabad',
            title: 'Patanjali',
            img: 'patanjali',
            key1: 'Cartons : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '113.75 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        },{
            location: 'Sasta Mart, Civil Lines, Allahabad',
            title: 'Sasta Mart',
            img: 'sasta_mart',
            key1: 'Duplex : ',
            key2: 'Cartons : ',
            key3: 'Polythene : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '13.54 kg',
            value2: '87 kg',
            value3: '14.35 kg',
            value4: '',
            value5: '',
            value6: ''
        }, {
            location: 'Anant Bazaar,Naini ,Allahabad',
            title: 'Anant Bazaar',
            img: 'anant_bazaar',
            key1: 'Recyclable Material : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '22 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        }, {
            location: 'Chaddha electric works',
            title: 'Chaddha electic works',
            img: 'Chaddha_electric_works',
            key1: 'Recyclable Material : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '91 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        }, {
            location: 'Housing, Allahabad',
            title: 'Housing',
            img: 'housing',
            key1: 'Recyclable Material : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '660 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        }, {
            location: 'Motilal & Sons, Allahabad',
            title: 'Motilal & Sons',
            img: 'mns',
            key1: 'Cartons : ',
            key2: 'Polythene : ',
            key3: '',
            key4: '',
            key5: '',
            key6: '',
            value1: '228.200 kg',
            value2: '4.3 kg',
            value3: '',
            value4: '',
            value5: '',
            value6: ''
        }, {
            location: 'Prince Dresses, Allahabad',
            title: 'Prince Dresses',
            img: 'prince',
            key1: 'Mix : ',
            key2: 'Duplex : ',
            key3: 'Books : ',
            key4: 'Cartons : ',
            key5: 'Newspaper : ',
            key6: 'Polythene : ',
            value1: '148.465 kg',
            value2: '141.445 kg',
            value3: '32.530 kg',
            value4: '15.695 kg',
            value5: '14.295 kg',
            value6: '72.730 kg'
        },{
            location: 'Mangalam, Allahabad',
            title: 'Mangalam',
            img: 'mangalam',
            key1: 'Carton : ',
            key2: 'Duplex : ',
            key3: 'Mix : ',
            key4: 'Polythene : ',
            key5: 'Books : ',
            key6: 'Newspaper : ',
            value1: '22.705 kg',
            value2: '6.120 kg',
            value3: '4.445 kg',
            value4: '1.775 kg',
            value5: '26.1 kg',
            value6: '2.425 kg'
        },{
            location: 'Ambika, Allahabad',
            title: 'Ambika Collections',
            img: 'ambika',
            key1: 'Carton : ',
            key2: 'Duplex : ',
            key3: 'Mix : ',
            key4: 'Polythene : ',
            key5: '',
            key6: 'Newspaper : ',
            value1: '7.315 kg',
            value2: '8.660 kg',
            value3: '17.120 kg',
            value4: '3.825 kg',
            value5: '',
            value6: '1 kg'
            
        },{
            location: 'Jai Lakshmi Collections, Allahabad',
            title: 'Jai Lakshmi Collections',
            img: 'jl',
            key1: 'Mix : ',
            key2: 'Duplex : ',
            key3: '',
            key4: '',
            key5: 'Newspaper : ',
            key6: 'Polythene : ',
            value1: '4.540 kg',
            value2: '6.115 kg',
            value3: '',
            value4: '',
            value5: '2.880 kg',
            value6: '4.120 kg'
        },{
            location: 'Lal garments, Allahabad',
            title: 'Lal garments',
            img: 'lal',
            key1: 'Mix : ',
            key2: '',
            key3: '',
            key4: '',
            key5: '',
            key6: 'Polythene : ',
            value1: '9.7 kg',
            value2: '',
            value3: '',
            value4: '',
            value5: '',
            value6: '1.945 kg'
        },{
            location: 'Saree Sansar, Allahabad',
            title: 'Ma Vidyavasini Saree Sansar',
            img: 'saree',
            key1: 'Carton : ',
            key2: 'Mix : ',
            key3: 'Polythene : ',
            key4: 'Duplex : ',
            key5: '',
            key6: '',
            value1: '14.975 kg',
            value2: '17.83 kg',
            value3: '10 kg',
            value4: '5.160 kg',
            value5: '',
            value6: ''
        },{
            location: 'Kesarwani Electricals, Allahabad',
            title: 'Kesarwani Electricals',
            img: 'kesarwani',
            key1: 'Carton : ',
            key2: 'Polythene : ',
            key3: 'Mix : ',
            key4: '',
            key5: '',
            key6: '',
            value1: '65.522 kg',
            value2: '2.008 kg',
            value3: '18.200 kg',
            value4: '',
            value5: '',
            value6: ''
        }
    ];
});